# Database URL
# spring.datasource.url=jdbc:sqlserver://KRISHNAPC\SQLEXPRESS01:1433;databaseName=IntegrityManagementTool;encrypt=true;trustServerCertificate=true;
spring.datasource.url = jdbc:sqlserver://localhost:1433;databaseName=IntegrityManagementTool;encrypt=true;trustServerCertificate=true

spring.datasource.username=SA
spring.datasource.password=Admin@123

# JDBC Driver
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.hikari.maximum-pool-size=5

# Hibernate Properties for sql server
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect

#File upload directory
spring.fileuploaddirectory.path = C:/Java/IntegrityTool/file-server

#Segment terminator
spring.segement.terminator = ~
spring.element.seperator = \\*

# EDIFile smooks-configuration file path
spring.smooks.configuration.path = classpath:EDIFileConfigurations/smooks-config.xml

# # Log to a specific file (log in the application's directory)
# logging.file.name=logs/IntegrityManagementTool.log

# # Set the root logging level (default is INFO)
# logging.level.root=INFO

# # Set the logging level for specific packages
# logging.level.com.myapp.service=DEBUG
# logging.level.com.myapp.controller=INFO

# # Set the logging level for specific classes
# logging.level.org.springframework.web=WARN
# logging.level.org.hibernate=ERROR

# # Tell Spring Boot where to find the Log4j2 configuration file
# logging.config=classpath:Logger/Logger.xml

# You can also turn off logging for a specific package/class
# logging.level.com.noisy.library=OFF