# Database URL
spring.datasource.url=jdbc:sqlserver://KRISHNAPC:1433;databaseName=BookstoreDB

# JDBC Driver
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate Properties for sql server
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect